name: GPTAreaOverview
channels:
  - defaults
dependencies:
  - python=3.8
  - tqdm
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - flask
  - ipywidgets
  - ipykernel
  - pyarrow
  - python-dotenv
  - pip:
    - openai
    - pymed
    - umap-learn
